enum Geometry {
  SHINOGI_ZUKURI,
  SHOBU_ZUKURI,
  HIRA_ZUKURI,
  KATA_KIRI_HA_ZUKURI,
  KIRI_HA_ZUKURI,
  MOROHA_ZUKURI,
  UNOKUBI_ZUKURI,
  TSUKURI_KOMI,
  KANMURIOTOSHI_SUKURI,
  KOGARASUMARU_ZUKURI,
  OSORAKU_ZUKURI,
  UNKNOWN
}